<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OluBitsFinOps.Application\OluBitsFinOps.Application.csproj" />
    <ProjectReference Include="..\oluBitsFinOps.Domain\oluBitsFinOps.Domain.csproj" />
  </ItemGroup>

</Project>
